### ISSUE TITLE
因http error 502无法匹配元数据

### ISSUE THREAD

**Issue by mike020020** [DoiiarX/NLCISBNPlugin#10]
calibre, version 7.10.0
错误： 无匹配项: <p>无法为你找到书籍元数据。请尝试<b>扩大搜索范围</b>。比如：只使用作者的姓氏或只包含书名中具有特征性的词。<p>要查看完整的日志，请点击“显示详情”。

Running identify query with parameters: 
{'title': '中国古典文学基本丛书002 杜诗详注（第四册）（[唐]杜甫撰，[清]仇兆鳌注，中华书局1999）', 'authors': ['[唐]杜甫撰，[清]仇兆鳌注'], 'identifiers': {}, 'timeout': 30} 
Using plugins: 国家图书馆ISBN插件 (1, 2, 1) 
The log from individual plugins is below 

****************************** 国家图书馆ISBN插件 (1, 2, 1) ****************************** 
Found 0 results 
Downloading from 国家图书馆ISBN插件 took 1.6326899528503418 
未检测到isbn。
正在根据书名获取metadata...
Plugin 国家图书馆ISBN插件 failed
Traceback (most recent call last):
  File "calibre\ebooks\metadata\sources\identify.py", line 47, in run
  File "calibre_plugins.dummy1.__init__", line 446, in identify
  File "calibre_plugins.dummy1.__init__", line 102, in title2metadata
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 634, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 502: Bad Gateway 

******************************************************************************** 
The identify phase took 1.80 seconds 
The longest time (1.632690) was taken by: 国家图书馆ISBN插件 
Merging results from different sources 
We have 0 merged results, merging took: 0.00 seconds

**Comment by DoiiarX** [comment]
## 解决办法

1. 尝试直接访问官网，查看自己是否被网站屏蔽
2. 尝试手动搜索，查看是否本身就是无结果

**Comment by DoiiarX** [comment]
还有人吗？没人就关了。
