### ISSUE TITLE
字符集异常导致下载失败

### ISSUE THREAD

**Issue by joey5403** [DoiiarX/NLCISBNPlugin#11]
Plugin 国家图书馆ISBN插件 failed
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/ebooks/metadata/sources/identify.py", line 47, in run
    self.plugin.identify(self.log, self.rq, self.abort, **self.kwargs)
  File "calibre_plugins.dummy4.__init__", line 446, in identify
    metadatas = title2metadata(title, log, result_queue, self.clean_downloaded_metadata,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dummy4.__init__", line 96, in title2metadata
    dynamic_url = get_dynamic_url(log)
                  ^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dummy4.__init__", line 83, in get_dynamic_url
    response_text = response.read().decode('utf-8')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by DoiiarX** [comment]
请留下具体的书籍。

这可能是因为下载的数据是被压缩的。

我需要具体的情况进行测试。

**Comment by DoiiarX** [comment]
您好。请提供具体书籍。

**Comment by joey5403** [comment]
> 您好。请提供具体书籍。

抱歉，我当时没有记住书名，后来看到您的回复，试了几个都没问题，然后我选了全库更新，结果可能是被封了ip。
本Issue先关闭了，等我下次发现，收集更多信息后再反馈。

最后，感谢您的优秀作品给我带来的帮助。
