### ISSUE TITLE
【403错误】获取元数据提示403错误

### ISSUE THREAD

**Issue by ruby109** [DoiiarX/NLCISBNPlugin#13]
我肉身在日本，能够访问国家图书馆的网页并进行搜索

```
****************************** 国家图书馆ISBN插件 (1, 2, 1) ****************************** 
Found 0 results 
Downloading from 国家图书馆ISBN插件 took 0.20234942436218262 
未检测到isbn。
正在根据书名获取metadata...
Plugin 国家图书馆ISBN插件 failed
Traceback (most recent call last):
  File "calibre\ebooks\metadata\sources\identify.py", line 47, in run
  File "calibre_plugins.dummy1.__init__", line 446, in identify
  File "calibre_plugins.dummy1.__init__", line 96, in title2metadata
  File "calibre_plugins.dummy1.__init__", line 82, in get_dynamic_url
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 634, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden 

```

是墙的原因吗

**Comment by DoiiarX** [comment]
403是服务器ban了你。

尝试访问：http://opac.nlc.cn/F
查看是否被ban。
一般来说隔一段时间就会恢复。
而且根据群友测试，实际上，人工访问也会有这个限制，所以问题不大。可以调整时间间隔、减小并发数。

群号：[491708665](http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=h30pFZuOws8XtP9kR13807pV9PsQQ_Gn&authKey=82bXfkY29udyKMXwVd6B2bd%2BOrsIo8rtPx7myJFH%2Fjhh%2BO5pNJlDqtZBo4wXM7R3&noverify=0&group_code=491708665)
