### ISSUE TITLE
下载原数据显示下载失败

### ISSUE THREAD

**Issue by czz404** [DoiiarX/NLCISBNPlugin#6]
```
calibre, version 7.3.0
错误： 下载失败: 无法下载元数据。请点击“显示详情”获取更多信息。

Traceback (most recent call last):
  File "calibre\utils\ipc\simple_worker.py", line 303, in main
  File "calibre\ebooks\metadata\sources\worker.py", line 58, in wrapper
  File "calibre\ebooks\metadata\sources\worker.py", line 119, in single_identify
  File "calibre\ebooks\metadata\sources\identify.py", line 499, in identify
  File "calibre\ebooks\metadata\sources\identify.py", line 367, in merge_identify_results
  File "calibre\ebooks\metadata\sources\identify.py", line 155, in finalize
  File "calibre\ebooks\metadata\sources\identify.py", line 249, in merge_isbn_results
  File "calibre\ebooks\metadata\sources\identify.py", line 351, in merge
  File "calibre\ebooks\metadata\book\base.py", line 169, in __getattribute__
AttributeError: Metadata object has no attribute named: 'identify'
```

**Comment by DoiiarX** [comment]
这个bug有点严重了，建议先回退版本。目前原因未知。

**Comment by czz404** [comment]
好的，v1.1.0 好像没问题，暂时先用老版本了

**Comment by DoiiarX** [comment]
重新试一试，解决了

**Comment by czz404** [comment]
解决了，感谢！
